version: '3.4'
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: user
      POSTGRES_PASSWORD: postgres
      PGDATA: /tmp
    ports:
      - "5432:5432"
    volumes:
      - ./data/dev:/var/lib/postgresql/data
  postgres-test:
    container_name: postgres-test
    image: postgres
    environment:
      POSTGRES_DB: todo_test
      POSTGRES_USER: user
      POSTGRES_PASSWORD: postgres
      PGDATA: /tmp
    ports:
      - "5435:5432"
    volumes:
      - ./data/test:/var/lib/postgresql/data
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://user:postgres@postgres:5432/todo
      NODE_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - postgres

